CREATE DATABASE QuanLyCuaHangNGK

USE QuanLyCuaHangNGK

CREATE TABLE NhaCungCap
(
	MaNCC NVARCHAR(25) PRIMARY KEY NOT NULL,
	TenNCC NVARCHAR(40),
	DiaChi NVARCHAR(50),
	SDT VARCHAR(20)
)

CREATE TABLE LoaiNuocGiaiKhat
(
	MaLoai NVARCHAR(25) PRIMARY KEY NOT NULL,
	TenLoai NVARCHAR(40),
	MaNCC NVARCHAR(25) FOREIGN KEY(MaNCC) REFERENCES NhaCungCap(MaNCC)
)

CREATE TABLE DonDatHang
(
	MaDDH NVARCHAR(25) PRIMARY KEY NOT NULL,
	NgayDH DATE,
	MaNCC NVARCHAR(25) FOREIGN KEY(MaNCC) REFERENCES NhaCungCap(MaNCC)
)

CREATE TABLE NuocGiaiKhat
(
	MaNGK NVARCHAR(25) PRIMARY KEY NOT NULL,
	TenNGK NVARCHAR(40),
	MaLoai NVARCHAR(25) FOREIGN KEY(MaLoai) REFERENCES LoaiNuocGiaiKhat(MaLoai)
)

CREATE TABLE ChiTietDonDatHang
(
	MaDDH NVARCHAR(25),
	MaNGK NVARCHAR(25),
	SoLuongDat INT,
	PRIMARY KEY(MaDDH,MaNGK),
	FOREIGN KEY (MaDDH) REFERENCES DonDatHang(MaDDH),
	FOREIGN KEY (MaNGK) REFERENCES NuocGiaiKhat(MaNGK)
)

CREATE TABLE PhieuGiaoHang
(
	MaPhieuGH NVARCHAR(25) PRIMARY KEY NOT NULL,
	MaDDH NVARCHAR(25) FOREIGN KEY(MaDDH) REFERENCES DonDatHang(MaDDH)
)

ALTER TABLE PhieuGiaoHang
ADD NgayGiao DATE

CREATE TABLE ChiTietPhieuGiaoHang
(
	MaPhieuGH NVARCHAR(25) FOREIGN KEY(MaPhieuGH) REFERENCES PhieuGiaoHang(MaPhieuGH),
	MaNGK NVARCHAR(25) FOREIGN KEY(MaNGK) REFERENCES NuocGiaiKhat(MaNGK),
	SoLuongGiao INT,
	DonGiaGiao FLOAT,
	PRIMARY KEY(MaPhieuGH,MaNGK)
)

CREATE TABLE KhachHang
(
	MaKH NVARCHAR(25) PRIMARY KEY NOT NULL,
	TenKH NVARCHAR(40),
	DiaChi NVARCHAR(50),
	SDT VARCHAR(15)
)

CREATE TABLE PhieuHen
(
	MaPhieuHen NVARCHAR(25) PRIMARY KEY NOT NULL,
	MaKH NVARCHAR(25) FOREIGN KEY(MaKH) REFERENCES KhachHang(MaKH),
	NgayLap DATE,
	NgayHen DATE
)

CREATE TABLE ChiTietPhieuHen
(
	MaPhieuHen NVARCHAR(25) FOREIGN KEY(MaPhieuHen) REFERENCES PhieuHen(MaPhieuHen),
	MaNGK NVARCHAR(25) FOREIGN KEY(MaNGK) REFERENCES NuocGiaiKhat(MaNGK),
	SoLuongHen INT,
	PRIMARY KEY(MaPhieuHen,MaNGK)
)

CREATE TABLE HoaDon
(
	MaHD NVARCHAR(25) PRIMARY KEY NOT NULL,
	NgayLapHD DATE,
	MaKH NVARCHAR(25) FOREIGN KEY(MaKH) REFERENCES KhachHang(MaKH)
)

CREATE TABLE ChiTietHoaDon
(
	MaHD NVARCHAR(25) FOREIGN KEY(MaHD) REFERENCES HoaDon(MaHD),
	MaNGK NVARCHAR(25) FOREIGN KEY(MaNGK) REFERENCES NuocGiaiKhat(MaNGK),
	SoLuongMua INT,
	DonGiaBan FLOAT,
	PRIMARY KEY(MaHD,MaNGK)
)

CREATE TABLE PhieuTraNo
(
	MaPhieuTraNo NVARCHAR(25) PRIMARY KEY NOT NULL,
	NgayTra DATE,
	SoTienTra FLOAT,
	MaHD NVARCHAR(25) FOREIGN KEY(MaHD) REFERENCES HoaDon(MaHD)
)

CREATE TABLE USERS
(
	TenDN VARCHAR(30) PRIMARY KEY NOT NULL,
	MatKhau VARCHAR(30)
)

INSERT INTO USERS VALUES
('Khoa','1'),
('Hoa','1'),
('Dat','1'),
('Bac','1')

